name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main      # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ── No build step needed for plain HTML ──

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src      # ← Point to your src folder
          cname: pass.castlefile.xyz  # ← Uncomment if you didn’t commit src/CNAME
